### ISSUE TITLE
Subscriber emotes from some channels don't show when I'm the one using them

### ISSUE THREAD

**Issue by LukyLurks** [Xithrius/twitch-tui#615] opened 2024-06-18 22:04 UTC
**Describe the bug:**
- Emotes from 2 of the 3 channels I am subscribed to remain in text form when I send them, and can't be found in the `Alt`+`e` menu.
- Emotes from these 2 channels show correctly when sent by other people.
- Emotes from these 2 channels show correctly in twitch-tui, when I send them through the twitch.tv chat (see screenshot)

**To Reproduce:**
I don't have reliable steps since it's my specific situation. The best I can suggest is:
1. Be subscribed to at least 2 channels.
2. Attempt to send messages containing the related subscriber emotes: emotes from one channel may remain in text form when sent.
3. Attempt to find the subscriber emotes in the popup menu: emotes from one channel may not be found.

**Expected behavior:**
- I expect emotes to display as images when sent, and to show up in the popup menu when searched.

**Screenshots:**
![sshot_2024_06_18_23_25_43](https://github.com/Xithrius/twitch-tui/assets/20930768/fc7daf0c-36ae-474d-9e94-7bb3b81b1a53)

**System:**

- Twitch-tui version: 2.6.11

- Operating System: Linux 6.9.5-arch1-1

- Terminal: kitty 0.35.1

- Shell: bash 5.2.26(1)-release

- config.toml:
```toml
[twitch]
username = "Luky75"
channel = "luky75"
server = "irc.chat.twitch.tv"
token = "redacted"

[terminal]
delay = 30
maximum_messages = 500
verbose = false
first_state = "Dashboard"

[storage]
channels = false
mentions = false

[filters]
enabled = false
reversed = false

[frontend]
show_datetimes = true
datetime_format = "%T"
username_shown = true
palette = "pastel"
title_shown = true
margin = 0
badges = true
theme = "dark"
username_highlight = true
state_tabs = false
cursor_shape = "user"
blinking_cursor = true
inverted_scrolling = false
show_scroll_offset = false
twitch_emotes = true
betterttv_emotes = true
seventv_emotes = false
frankerfacez_emotes = true
favorite_channels = []
recent_channel_count = 5
border_type = "plain"
hide_chat_border = true
right_align_usernames = false
show_unsupported_screen_size = true
```

**Additional context:**
- If this issue is hard to diagnose on your own because you're not subscribed to multiple channels, feel free to ask me to do "technical" stuff. I don't know much about Rust, therefore I'd be happy to have an excuse to get into it.

**Comment by Xithrius** [comment] 2024-06-18 22:37
Hello, and thanks for the issue! Before actual diagnosis of code or anything, how did you generate your token?

**Comment by Xithrius** [comment] 2024-06-18 22:40
Oops, I see that you're the same author as #611. I don't think additional scopes are needed, so you did generate your token properly.

**Comment by Xithrius** [comment] 2024-06-18 22:42
Might be an issue between the current and previous minor versions of twitch-tui. Could you remove the cache located at `~/.cache/twt`? 2.6.11 requires a cleared cache for subscriber emotes to work properly.

**Comment by LukyLurks** [comment] 2024-06-18 23:22
I actually generated a different token since. When I noticed the issue I am describing here, I suspected that https://twitchapps.com/tmi/ wasn't giving me enough scopes, so I generated another one with https://twitchtokengenerator.com instead, with the following scopes: `chat:edit`, `chat:read`, `user:read:chat`, `user:read:emotes`, `user:read:emotes`, `user:read:follows`, `user:read:subscriptions`, `user:write:chat`. This is the token used for this bug report, and that I currently use in my config.
I also made sure `$TWT_TOKEN` wasn't set to some old token (it is unset).

> Could you remove the cache located at ~/.cache/twt? 2.6.11 requires a cleared cache for subscriber emotes to work properly.

I quit `twt`, did `rm -r ~/.cache/twt/`, started `twt`, and tried to send dekillKermit and search it in the popup menu: the issue persists.

**Comment by Xithrius** [comment] 2024-06-19 00:21
Alright, looks like I'll have to dig deeper then.

**Comment by Xithrius** [comment] 2024-06-21 08:48
@Nogesma I think #591 might be the cause of this problem, but I'm not 100% sure. If you could give any insight, I'd very much appreciate it.

Besides that, @LukyLurks have you tried other recent versions, such as 2.6.10?

**Comment by LukyLurks** [comment] 2024-06-21 09:55
- with 2.6.12: seemingly the same behavior as with 2.6.11 except I didn't check what happens when others send subscriber emotes (let me know if you'd like me to check).
- with 2.6.10: subscriber emotes always show as text in twitch-tui when I send them, even when I send them from twitch.tv. Again I didn't check what happens when other people send them.

**Comment by Xithrius** [comment] 2024-06-21 09:57
Could you do the check for seeing what happens when others send subscriber emotes? Thanks.

**Comment by Xithrius** [comment] 2024-06-21 10:01
I also noticed in your config that you have `seventv_emotes` set to `false`. I'm not certain that this would fix your issue, but have you tried setting it to true?

**Comment by Nogesma** [comment] 2024-06-21 10:02
Before 2.6.11 there wasn't any checks for if users actually could send those emotes, so twt displayed subscriber emotes from the current channel for everyone.
I'll try to see if I'm using the wrong api to get subscriber emotes. I'll let you know if I need any more info figuring that one out.

**Comment by Nogesma** [comment] 2024-06-21 10:48
I just pushed a draft PR with what I think fixes it, could you please try it?

**Comment by LukyLurks** [comment] 2024-06-21 14:20
@Nogesma It seems to be working. The emotes appear in the popup search, and they show correctly when sent. People's subscriber emotes (both from the current channel and different channels) seem to be showing correctly as well.


@Xithrius
- Toggling `seventv_emotes` seemingly did nothing with versions 2.6.10, 2.6.11, 2.6.12, Nogesma's PR #616.
- Regarding other people sending subscriber emotes: with 2.6.10 if the emotes are from the current channel they show correctly, and if they're from a different channel they don't. 2.6.12 behaves like 2.6.11.

Thank you both!

**Comment by Xithrius** [comment] 2024-06-21 17:17
Thank you so much for going through each version for testing. I'll be testing the PR myself later today, and if all is good then I'll do a release as soon as I can once it's merged.

**Closed** 2024-06-22 18:32 UTC

**Comment by Xithrius** [comment] 2024-06-22 18:38
Fix available in https://github.com/Xithrius/twitch-tui/releases/tag/v2.6.13

**Comment by Xithrius** [comment] 2024-06-22 18:39
Thank you @LukyLurks for the issue, and @Nogesma for the fix!
